name: "Release and Deploy"
on:
  push:
    branches:
      - "master"

jobs:
  release-and-deploy: 
    runs-on: "ubuntu-22.04"
    timeout-minutes: 60
    steps: 
      - name: "Checkout code"
        uses: "actions/checkout@v3"
        with:
          fetch-depth: 0

      - name: "Set up Nix"
        uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: "Run flake checks"
        run: "nix flake check --show-trace"

      - name: "Set up git user email"
        run: > 
          nix develop -c 
          git config --global user.email 'maciej.laciak@gmail.com'

      - name: "Set up git user name" 
        run: > 
          nix develop -c 
          git config --global user.name 'mstream'

      - name: "Install dependencies"
        run: > 
          nix develop -c 
          npm ci

      - name: "Run linters"
        run: >
          nix develop -c 
          npm run lint

      - name: "Run unit tests"
        run: >
          nix develop -c 
          npm run test:purs

      - name: "Bundle web application"
        run: >
          nix develop -c 
          npm run bundle:production:webapp

      - name: "Run UI tests"
        run: >
          nix develop -c 
          npm run test:ui:production
          
      - name: "Save Playwright reports" 
        uses: "actions/upload-artifact@v3"
        if: "failure()"
        with:
          name: "playwright-report"
          path: "playwright-report/"
          retention-days: 7

      - name: "Create a GitHub release"
        run: >
          nix develop -c 
          npm run release -- --ci
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Deploy to GitHub Pages"
        uses: "peaceiris/actions-gh-pages@v3"
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          publish_dir: "./dist"

